package hw18;

public enum Position {
    ORTHODONTIST,
    GASTROENTEROLOGIST,
    CARDIOLOGIST,
    OPHTHALMOLOGIST,
    DERMATOLOGIST,
    SURGEON,
    NURSE,
    DENTIST,
    PSYCHOTHERAPIST,
    NEUROLOGIST,
    MIDWIFE
}
